package com.vaadin.example.documentmanager;

import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.declarative.Design;

/**
 * Generated by Vaadin Designer. This class is managed by Vaadin Designer and
 * you must not alter it. Anyway, your changes will be removed, so it matters
 * less.
 */
@DesignRoot
public class EditorDesign extends TabSheet {
    public RichTextArea rich;
    public TextArea html;

    public EditorDesign() {
        Design.read(this);
    }
}
